---
apiVersion: v1
kind: Service
metadata:
  name: nginx-docker
spec:
  selector:
    role: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-docker
  labels:
    role: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nginx-app
  template:
    metadata:
      labels:
        role: nginx-app
    spec:
      containers:
      - name: app
        image: snaredla89/p1:latest
